version: "3"
services:
  

  # Dia-Mat starts in development mode
  diamat-dev:
    container_name: 'diamat-dev'
    image: 'emilianscheel/diamat:latest'
    restart: always
    env_file:
      - '~/.diamat/1/.env.local'
      - '~/.diamat/1/.env.development.local'
    volumes:
      - '~/.diamat/1/diamat-data/:/app/diamat-data/'
    ports:
      - "3200:3000"
    command: npm run dev