version: "3"
services:


  # Dia-Mat starts in production mode
  diamat-prod:
    container_name: 'diamat-prod'
    depends_on:
      - mongodb
    image: 'emilianscheel/diamat:latest'
    env_file:
      - '~/.diamat/1/.env.local'
      - '~/.diamat/1/.env.production.local'
    ports:
      - "3200:3000"
    command: npm run build && npm run start 
