version: "3"
services:
  

  # Dia-Mat starts in development mode
  diamat-dev:
    container_name: 'diamat-dev'
    depends_on:
      - mongodb
    image: 'emilianscheel/diamat:latest'
    env_file:
      - '~/.diamat/1/.env.local'
      - '~/.diamat/1/.env.development.local'
    ports:
      - "3200:3000"
    command: npm run dev