version: "3"
services:

  # MongoDB instance for Dia-Mat
  mongodb:
    image: 'mongo:latest'
    container_name: 'diamat-mongodb'
    environment:
      - MONGO_INITDB_DATABASE=diamat-db
      - MONGO_USERNAME=diamat-user
      - MONGO_PASSWORD=KfvzCbQS9hGkrkJm
    volumes:
      - '~/.diamat/1/mongodb/:/data/db/'
      - '~/.diamat/1/mongodb-init/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh'
      - '~/.diamat/1/mongodb-init/data/:/tmp/data/'
    ports:
      - '3201:27017'
