version: "3"
services:


  # Dia-Mat starts in production mode
  diamat-prod:
    container_name: 'diamat-prod'
    image: 'emilianscheel/diamat:latest'
    restart: always
    env_file:
      - '~/.diamat/1/.env.local'
      - '~/.diamat/1/.env.production.local'
    ports:
      - "3200:3200"
    command: > 
      bash -c "npm run build && npm run start"
